### ISSUE TITLE
Repository history - Rebase ?

### ISSUE THREAD

**Issue by quadrifoglio** [quadrifoglio/rust-book-fr#2]
Hi everyone,

The git history of this french translation repository is a bit of a mess.
Although our translation commits happen on a dedicated branch, one for each chapter, the current strategy is that eventually those branches get merged into master after their review.
This results in our work being diluted with the original writers' work, in the master branch.

I was thinking that maybe it would be better to create a branch dedicated to our translation work, called something like "french". The idea is that we merge our translation commits into that branch via the usual PR process, therefore keeping our work separate from the original team's work.

I would periodically rebase that "french" branch on the English repository's master branch in order to keep the original chapters' source up to date, and our translation commits would be easily distinguishable as they would come first in the git history.

What do you think of that idea ? Do you see any benefits or drawbacks ?
Thanks, and have a nice evening !

@asettouf @Jimskapt

**Comment by Jimskapt** [comment]
Yes, I think it's a good idea, you right, it will be clearer, that way !

But, I think ... There is not "previous" commits of original writer's when we are merging on this branch ? (because we are based on their commits)

I know that there is an option in GitHub to set up this branch as replacement of default "master" view, I think it will be usefull in this case.

**Comment by asettouf** [comment]
@Jimskapt 

Not sure I understand which branch you are talking about, because if you take the [master](https://github.com/quadrifoglio/rust-book-fr/commits/master) branch (where my PR is already merged) you clearly see my commits diluted with the original repo.

@quadrifoglio 

Seems like a good idea to me, let's go for it. I guess the name "french-release" for the branch would be fine. What do you think?

**Comment by Jimskapt** [comment]
@asettouf 

> you clearly see my commits diluted with the original repo

Yes, I mean, it will be a problem to see our "French commits" and also "English commits", because, when we will update from "original repo", we'll see the new "English commits" on top of our "French commits", right ?

**Comment by quadrifoglio** [comment]
> we'll see the new "English commits" on top of our "French commits", right ?

@Jimskapt No we won't, since we will rebase on the original repo's master branch, not merge with it.

Okay, so I did the work. The name of our french translation branch is "fr-release", that is the one that will regularly be rebased on the original repository's master, and that will receive translation PRs.

Also, I created new up-to-date branches for every chapter that is currently being worked on, following the naming convention "fr-chXX" (XX = chapter number).

So, @Jimskapt @asettouf @ShinySaana, please check your respective new branches (fr-chXX) to make sure that I did not mess anything up.

Once we are sure that everyone's work is safe in the new branches, we can delete the old ones and set "fr-release" as the default.

Thanks !

**Comment by asettouf** [comment]
@quadrifoglio 

I'm reviewing chapter 4 and as I can see the ch04-00 translation had not been integrated into fr-ch04. I just pushed it on the branch. Let me know if it's ok as I made a new commit (perhaps you want to keep the commit history intact)

Chapter 13 seems ok to me (I just skimmed through though)

**Comment by quadrifoglio** [comment]
Oh sorry, I must have screwed up while rebasing.
I dont't think we need do really worry about the commit history, as long as ours is distinguishable from the original one

**Comment by Jimskapt** [comment]
@quadrifoglio Hi, looks like I have the same issue : the ch07-00 in `fr_translating_ch07` branch was not pulled up to the `fr-ch07` branch :-)

**Comment by quadrifoglio** [comment]
Ok, I deleted the old branches and set fr-release as the default branch. Thanks everyone !
